{% set name = "mumax3c" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f81786cb89c48d1da96a5b790d15b86c5228cfce3ce80ee066dba1f26728ce3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - micromagneticmodel >=0.64.0
    - micromagnetictests >=0.63.2
    - scipy
    - ubermagtable >=0.61.4
    - ubermagutil >=0.63.4

test:
  imports:
    - mumax3c
  commands:
    - pip check
    # running unittests would require a GPU and a separate Mumax3 installation
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://ubermag.github.io/
  summary: Python interface to mumax3 integrated into Jupyter notebook.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://ubermag.github.io/documentation/mumax3c.html
  dev_url: https://github.com/ubermag/mumax3c

extra:
  recipe-maintainers:
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
